<?php include 'config.php';?>
<!DOCTYPE html>

<html>
	<head>
		<!-- -----------------------------META REGION------------------------------ -->

		<meta http-equiv="Content-Type" content="text/html; charset=utf-8"> <!--ESTABLECEMOS LA CODIFICACION A UTF-8-->
		<meta name="author" content="Watchandcoment Team"><!-- AUTORES DE LA PÁGINA -->

	<!-- ----------------------------- END META REGION------------------------------ -->


	<!-- -----------------------------LINKS REGION------------------------------ -->
		<link rel="shortcut icon" type="image/x-icon" href="<?php echo RAIZ_APP; ?>img/favicon.ico"> <!-- ESTABLECIMIENTO DEL FAVICON -->

		<link rel="stylesheet" type="text/css" href="<?php echo RAIZ_APP; ?>css/login.css"><!-- LINK AL ESTILO DE ESTA PAGINA -->
		<link rel="stylesheet" type="text/css" href="<?php echo RAIZ_APP; ?>css/header.css"><!-- LINK AL ESTILO DE ESTA PAGINA -->
		<link rel="stylesheet" type="text/css" href="<?php echo RAIZ_APP; ?>css/style.css"><!-- LINK AL ESTILO DE ESTA PAGINA -->
		<link rel="stylesheet" type="text/css" href="<?php echo RAIZ_APP; ?>css/menu.css"><!-- LINK AL ESTILO DE ESTA PAGINA -->
		<link rel="stylesheet" type="text/css" href="<?php echo RAIZ_APP; ?>css/footer.css"><!-- LINK AL ESTILO DE ESTA PAGINA -->
		<script src="http://code.jquery.com/jquery-latest.min.js" type="text/javascript"></script>
		<script src="<?php echo RAIZ_APP; ?>js/sidebarIzq.js" type="text/javascript"></script>


	<!-- -----------------------------END LINKS REGION------------------------------ -->

		<title>Condiciones y términos de uso</title>
	</head>
	<body>
		<div id = "contenedor">
			<!-- INCLUDE CABECERA -->
			<?php include_once __DIR__ .'/header.php'; ?>						
	
			<!-- Menu izq -->
			<?php include_once __DIR__ .'/sidebarIzq.php'; ?>	
			<!-- CONTENIDO -->
			<div id = "contenido">
			
			<div id = "titulo">
				Términos y condiciones de uso de Watch & Comment
			</div>
				<div id="texto">
					<h1>	Los siguientes términos y condiciones rigen el uso que usted le dé a este sitio web y a cualquiera de los contenidos disponibles por o a través de este sitio web, incluyendo cualquier contenido derivado del mismo.</h1>
					W&C. Podemos cambiar los Términos y Condiciones de vez en cuando, en cualquier momento sin ninguna notificación, sólo publicando los cambios en el Sitio Web. AL USAR EL SITIO WEB, USTED ACEPTA Y ESTÉ DE ACUERDO CON ESTOS TÉRMINOS Y CONDICIONES EN LO QUE SE REFIERE A SU USO DEL SITIO WEB. Si usted no está de acuerdo con estos Términos y Condiciones, no puede tener acceso al mismo ni usar el Sitio Web de ninguna otra manera.
						 <dl>
						<u>1.         Derechos de Propiedad. </u> Entre usted y W&C., W&C. es dueño único y exclusivo, de todos los derechos, título e intereses en y del Sitio Web, 
						de todo el contenido (incluyendo, por ejemplo, audio, fotografías, ilustraciones, gráficos, otros medios visuales, videos,
						copias, textos, software, títulos, archivos de Onda de choque, etc.), códigos, datos y materiales del mismo, el aspecto y el ambiente, el diseño y 
						la organización del Sitio Web y la compilación de los contenidos, códigos, datos y los materiales en el Sitio Web, incluyendo pero no limitado a, cualesquiera derechos de autor, derechos de marca, derechos de patente, derechos de base de datos, derechos morales, derechos sui generis y otras propiedades intelectuales y derechos patrimoniales del mismo. Su uso del Sitio Web no le otorga propiedad de ninguno de los contenidos, códigos, datos o materiales a los que pueda acceder en o a través del Sitio Web.</dl>
						 <dl>
						<u>2.         Licencia Limitada.</u> Usted puede acceder y ver el contenido del Sitio Web desde su computadora o desde cualquier otro aparato y, a menos de que se indique de otra manera en estos Términos y Condiciones o en el Sitio Web, sacar copias o impresiones individuales del contenido del Sitio Web para su uso personal, interno únicamente. El uso del Sitio Web y de los servicios que se ofrecen en o a través del Sitio Web, son sólo para su uso personal, no comercial.</dl>
						<dl> 
						<u>3.         Uso Prohibido. </u>Cualquier distribución, publicación o explotación comercial o promocional del Sitio Web, o de cualquiera de los contenidos, códigos, datos o materiales en el Sitio Web, está estrictamente prohibida, a menos de que usted haya recibido el previo permiso expreso por escrito del personal autorizado de W&C. o de algún otro poseedor de derechos aplicable. A no ser como está expresamente permitido en el presente contrato, usted no puede descargar, informar, exponer, publicar, copiar, reproducir, distribuir, transmitir, modificar, ejecutar, difundir, transferir, crear trabajos derivados de, vender o de cualquier otra manera explotar cualquiera de los contenidos, códigos, datos o materiales en o disponibles a través del Sitio Web. Usted se obliga además a no alterar, editar, borrar, quitar, o de otra manera cambiar el significado o la apariencia de, o cambiar el propósito de, cualquiera de los contenidos, códigos, datos o materiales en o disponibles a través del Sitio Web, incluyendo, sin limitación, la alteración o retiro de cualquier marca comercial, marca registrada, logo, marca de servicios o cualquier otro contenido de propiedad o notificación de derechos de propiedad. Usted reconoce que no adquiere ningún derecho de propiedad al descargar algún material con derechos de autor de o a través del Sitio Web. Si usted hace otro uso del Sitio Web, o de los contenidos, códigos, datos o materiales que ahí se encuentren o que estén disponibles a través del Sitio Web, a no ser como se ha estipulado anteriormente, usted puede violar las leyes de derechos de autor y otras leyes de los Estados Unidos y de otros países, así como las leyes estatales aplicables, y puede ser sujeto a responsabilidad legal por dicho uso no autorizado.</dl>
						<dl> 
						<u>4.         Marcas Comerciales.</u> Las marcas comerciales, logos, marcas de servicios, marcas registradas (conjuntamente las "Marcas Comerciales") expuestas en el Sitio Web o en los contenidos disponibles a través del Sitio Web son Marcas Comerciales de W&C. registradas y no registradas y otras, y no pueden ser usadas con respecto a productos y/o servicios que no estén relacionados, asociados o patrocinados por sus poseedores de derechos y que puedan causar confusión a los clientes, o de alguna manera que denigre o desacredite a sus poseedores de derechos. Todas las Marcas Comerciales que no sean de W&C. que aparezcan en el sitio Web o en o a través de los servicios del Sitio Web, si las hubiera, son propiedad de sus respectivos dueños. Nada que esté contenido en el Sitio Web deberá ser interpretado como otorgando, por implicación, desestimación, o de otra manera, alguna licencia o derecho para usar alguna Marca Comercial expuesta en el Sitio Web sin el permiso escrito de W&C. o de terceros que puedan ser dueños de dicha Marca Comercial. El mal uso de las Marcas Comerciales expuestas en el Sitio Web o en o a través de cualquiera de los servicios del Sitio Web está estrictamente prohibido.</dl>
						<dl> 
						<u>5.         Información del Usuario.</u> En el curso del uso que usted haga del Sitio Web y/o de los servicios puestos a su disposición en o a través del Sitio Web, se le puede pedir que nos proporcione cierta información personalizada (dicha información en lo sucesivo "Información del Usuario"). Las políticas de uso y recopilación de información de W&C. con respecto a la privacidad de dicha Información del Usuario se establecen en la Política de Privacidad del Sitio Web, la cual está incorporada al mismo como referencia para todos los propósitos. Usted reconoce y acepta ser el único responsable de la exactitud del contenido de la Información del Usuario.</dl>
						<dl> 
						<u>6.         Materiales Presentados.</u> A menos que se solicite específicamente, no pedimos ni deseamos recibir ninguna información confidencial, secreta o patrimonial, ni otro material de usted a través del Sitio Web, por correo electrónico o de cualquier otra manera. Cualquier información, trabajos creativos, demostración, ideas, sugerencias, conceptos, métodos, sistemas, diseños, planes, técnicas u otros materiales que nos haya mandado o presentado (incluyendo, por ejemplo y sin limitación, aquello que usted presenta o envía a nuestros grupos de chateo, tablas de mensajes y/o a nuestros ‘blogs’, o que nos manda vía correo electrónico) ("Materiales Presentados") se considerará como no confidencial o secreto y que puede ser usado por nosotros de cualquier manera consistente con la Política de Privacidad del Sitio Web. Al presentarnos o mandarnos Materiales Presentados, usted: (i) representa y garantiza que los Materiales Presentados son originales suyos, que ninguna otra persona tiene ningún derecho sobre ellos, y que cualquier "derecho moral" sobre los Materiales Presentados ha sido renunciado, y (ii) usted nos concede, a nosotros y a nuestros afiliados, derecho y licencia libres de regalías, sin restricciones, mundiales, perpetuos, irrevocables, no exclusivos y totalmente transferibles, que pueden ser cedidos y sub-licenciados, para usar, copiar, reproducir, modificar, adaptar, publicar, traducir, crear trabajos derivados de, distribuir, ejecutar, exponer e incorporar en otros trabajos cualquiera de los Materiales Presentados (todos o en parte) en cualquier forma, medio o tecnología no conocida o por desarrollar, incluyendo propósitos promocionales y/o comerciales. No podemos ser responsables de conservar ningún Material Presentado proporcionado por usted y podemos borrar o destruir dicho Material Presentado en cualquier momento.
						 </dl>
						 <dl>
						<u>7.         Conducta Prohibida del Usuario.</u> Usted garantiza y está de acuerdo en que, mientras use el Sitio Web y los diversos servicios y artículos que se ofrecen en o a través del Sitio Web, usted no: (a) personalizará a ninguna persona o entidad ni desvirtuará su afiliación con alguna otra persona o entidad; (b)  insertará su propio anuncio, posicionamiento de marca o algún otro contenido promocional o el de un tercero  en cualquiera de los contenidos, materiales o servicios o materiales del Sitio Web (por ejemplo, sin limitación, en una actualización RSS o en un programa de radio grabado (podcast) recibido de W&C. o de algún otro modo a través del Sitio Web), ni usará, redistribuirá, republicará o explotará dichos contenidos o servicios con cualquier otro propósito adicional comercial o promocional; ni (c) intentará ganar acceso no autorizado a otros sistemas de cómputo a través del Sitio Web. Usted no: (i) participará en navegar por la red, en "raspar (scraping) la pantalla", "raspar (scraping) la base da datos", en recolectar direcciones de correo electrónico, direcciones inalámbricas u otra información personal o de contactos, o cualquier otro medio automático de obtener listas de usuarios u otra información de o a través del sitio Web o de los servicios ofrecidos en o a través del Sitio Web, incluyendo, sin limitación, cualquier información que se encuentre en algún servidor o base de datos relacionada con el Sitio Web o los servicios ofrecidos en o a través del Sitio Web; (ii) obtendrá o intentará obtener acceso no autorizado a los sistemas de cómputo, materiales o información por cualquier medio; (iii) usará el Sitio Web o los servicios puestos a su disposición en o a través del Sitio Web de alguna manera con la intención de interrumpir, dañar, deshabilitar, sobrecargar o deteriorar el Sitio Web o dichos servicios, incluyendo, sin limitación, mandar mensajes masivos no solicitados o "inundar" servidores con solicitudes; (iv) usará el Sitio Web o los servicios o artículos del Sitio Web en violación de la propiedad intelectual o de otros derechos legales o patrimoniales de W&C o de algún tercero; ni (v) usará el Sitio Web o los servicios del Sitio Web en violación de cualquier ley aplicable. Usted se obliga además, a no intentar (o alentar o apoyar el intento de otro) a embaucar, destruir, decodificar, o de otro modo alterar o interferir con el Sitio Web o con los servicios del Sitio Web, o con cualquier contenido del mismo, o hacer cualquier uso no autorizado del mismo. Usted se obliga a no usar el Sitio Web de alguna manera que pudiera dañar, deshabilitar, sobrecargar o deteriorar el Sitio Web o interferir con que cualquier otra persona pueda usar o disfrutar del Sitio Web o de cualquiera de sus servicios. Usted no obtendrá ni intentará obtener algún material o información a través de cualquier medio que no haya sido estipulado o puesto a la disposición del público intencionalmente a través del Sitio Web.
						 </dl>
						 <dl>
						<u>8.         Foros Públicos.</u> W&C. puede, de vez en cuando, tener servicios de mensajería, servicios de chateo, tableros de noticias, blogs, otros foros y otros servicios disponibles en o a través del Sitio Web. Además de cualquier otra normatividad y regulación que podamos publicar con respecto a un servicio en particular, usted se obliga a no cargar, informar, transmitir, distribuir o de otra manera publicar a través del Sitio Web o de cualquier servicio o artículo puesto a la disposición en o a través del Sitio Web, cualquier material que (i) restrinja o inhiba a cualquier otro usuario de usar y disfrutar del Sitio Web o de los servicios del Sitio Web, (ii) sea fraudulento, ilegal, amenazante, abusivo, hostigante, calumnioso, difamatorio, obsceno, vulgar, ofensivo, pornográfico, profano, sexualmente explícito o indecente, (iii) constituya o aliente conductas que pudieran constituir una ofensa criminal, dar lugar a responsabilidad civil o de otro modo violar cualquier ley local, estatal, nacional o internacional, (iv) viole, plagie o infrinja los derechos de terceros incluyendo, sin limitación, derechos de autor, marcas comerciales, secretos comerciales, confidencialidad, contratos, patentes, derechos de privacidad o publicidad o cualquier otro derecho de propiedad, (v) contenga un virus, elemento de espionaje u otro componente dañino, (vi) contenga enlaces fijos, publicidad, cartas de cadenas o esquemas de pirámides de cualquier tipo, o (vii) constituya o contenga indicaciones de origen, endosos o declaraciones de hechos falsos o engañosos. Usted además se obliga a no personificar a cualquier otra persona o entidad, ya sea real o ficticia, incluyendo cualquier persona de W&C. Usted tampoco puede ofrecer comprar o vender algún producto o servicio en o a través de sus comentarios presentados en nuestros foros. Solamente usted es responsable del contenido y de las consecuencias de cualquiera de sus actividades.
						 </dl>
						 <dl>
						<u>9.         Derecho de Monitoreo y Control Editorial.</u> W&C. se reserva el derecho, pero no tiene la obligación, de monitorear y/o revisar todos los materiales enviados al Sitio Web o a través de los servicios o artículos del Sitio Web por los usuarios, y W&C. no es responsable de dichos materiales enviados por los usuarios. Sin embargo, W&C. se reserva el derecho en todo momento de divulgar cualquier información que sea necesaria para satisfacer cualquier ley, reglamento o solicitud gubernamental, o de editar, rehusarse a colocar o a quitar cualquier información o materiales, todos o en parte, que a discreción únicamente de W&C. sean censurables o en violación de estos Términos de Uso, de las políticas de W&C o de la ley aplicable. También podemos imponer límites sobre ciertos artículos de los foros o restringir su acceso a parte o a todos los foros sin notificación o sanción, si creemos que usted está en incumplimiento de las directrices establecidas en este párrafo, nuestros términos y condiciones o la ley aplicable, o por cualquier otra razón sin notificación o responsabilidad.
						 </dl>
						 <dl>
						<u>10.      Información Privada o Delicada en Foros Públicos.</u> Es importante recordar que los comentarios presentados en un foro pueden ser registrados y almacenados en múltiples lugares, tanto en nuestro Sitio Web como en otra parte en Internet, los cuales pueden ser accesibles durante mucho tiempo y no se tiene control sobre quién los leerá eventualmente. Es por lo tanto importante que tenga usted cuidado y sea selectivo acerca de la información personal que divulgue acerca de usted y de otros, y en especial, no debe divulgar información delicada, patrimonial o confidencial en sus comentarios en nuestros foros públicos.
						 </dl>
						 <dl>
						<u>11.      Enlaces con el Sitio Web.</u> Usted está de acuerdo en que si incluye un enlace (link) de cualquier otro sitio web al Sitio Web, dicho enlace se abrirá en una nueva ventana navegadora y se enlazará con la versión completa de una página formateada HTML de este Sitio Web. Usted no tiene permitido enlazarse directamente a ninguna imagen almacenada en el Sitio Web o en nuestros servicios, como sería usar un método de enlace "en-línea" para provocar que la imagen almacenada por nosotros fuera expuesta en otro sitio web. Usted se obliga a no descargar o usar imágenes almacenadas en este Sitio Web en otro sitio web, con cualquier propósito, incluyendo, sin limitación, publicar dichas imágenes en otro sitio web. Usted se obliga a no enlazarse de cualquier otro sitio web a este Sitio Web de tal manera que el Sitio Web, o cualquier página del Sitio Web, esté "enmarcado", rodeado u ofuscado por los contenidos, materiales o posicionamientos de marca de cualquier tercero. Nos reservamos todos nuestros derechos bajo la ley para insistir en que cualquier enlace al Sitio Web sea descontinuado y a revocar su derecho a enlazarse al Sitio Web de cualquier otro sitio web, en cualquier momento en el que le mandemos notificación por escrito.
						 </dl>
						 <dl>
						<u>12.      Indemnización.</u> Usted se obliga a defender, indemnizar y a sacar a W&C. y a los directores, funcionarios, empleados y agentes de W&C. y sus afiliados en paz y a salvo de cualquier demanda, responsabilidad, costos y gastos, de cualquier naturaleza, incluyendo honorarios de abogados, en que incurriera como resultado del uso del Sitio Web, su colocación o transmisión de cualquier mensaje, contenido, información, software u otros materiales a través del Sitio Web, o su incumplimiento o violación de la ley o de estos Términos y Condiciones. W&C. se reserva el derecho, a su propio costo, de asumir la defensa y control exclusivos de cualquier asunto de otra manera sujeto a indemnización por parte suya, y en dicho caso, usted se obliga a cooperar con W&C. en la defensa de dicha demanda.
						 </dl>
						 <dl>
						<u>13.      Órdenes de Productos y Servicios.</u> Podemos poner ciertos productos a la disposición de visitantes y registrados del Sitio Web. Si usted ordena cualquier producto, por el presente documento usted representa y garantiza que tiene 18 años de edad o más. Se obliga a pagar la totalidad de los precios de cualquier compra que haga, ya sea con tarjeta de crédito/débito concurrente con su orden en línea o por otro medio de pago aceptable para W&C. Usted se obliga a pagar todos los impuestos aplicables. Si el pago no es recibido por nosotros de parte del emisor de su tarjeta de crédito o débito o de sus agentes, usted se obliga a pagar todas las cantidades debidas al momento de la reclamación por nuestra parte. Algunos productos que usted compra y/o descarga en o a través del Sitio Web pueden estar sujetos a términos y condiciones adicionales que le serán presentados al momento de dicha compra o descarga.
						 </dl>
						 <dl>
						<u>14.      Sitios Web de Terceros.</u> Usted puede enlazar (link) del Sitio Web a sitios web de terceros y terceros pueden enlazarse al Sitio Web ("Sitios Enlazados"). Usted reconoce y está de acuerdo en que nosotros no tenemos responsabilidad sobre la información, contenido, productos, servicios, anuncios, códigos u otros materiales que puedan o no puedan ser proporcionados por o a través de los Sitios Enlazados, aún si son propiedad de o son dirigidos por afiliados nuestros. Los enlaces (links) a Sitios Enlazados no constituyen un aval o patrocinio nuestro de dichos sitios web o de la información, contenido, productos, servicios, anuncios, códigos u otros materiales presentados en o a través de dichos sitios web. La inclusión de cualquier enlace a dichos sitios en nuestro Sitio no implica el aval, patrocinio o recomendación de ese sitio de W&C. W&C. rechaza cualquier responsabilidad por los enlaces (1) de otro sitio web a este Sitio Web y (2) a otro sitio web de este Sitio Web. W&C. no puede garantizar los estándares de cualquier sitio web al cual se le proporcionen enlaces en este Sitio Web, ni será W&C. responsable de los contenidos de dichos sitios, o de cualquier enlace subsecuente. W&C. no representa o garantiza que los contenidos del sitio web de algún tercero sean exactos, que cumplan con la ley estatal o federal, o que cumplan con las leyes de derechos de autor o con otras leyes de propiedad intelectual. W&C. tampoco es responsable de cualquier forma de transmisión recibida de cualquier sitio web enlazado. Cualquier confianza depositada en los contenidos de un sitio web de terceros es hecha por su propio riesgo y usted asume todas las responsabilidades y consecuencias que resulten de dicha confianza.
						 </dl>
						 <dl>
						<u>15.      Agente de Derechos de Autor.</u>
						 
						Respetamos los derechos de propiedad intelectual de otros y requerimos que las personas que usen el Sitio Web, o los servicios o artículos puestos a su disposición en o a través del Sitio Web, hagan lo mismo. Si usted cree que su trabajo ha sido copiado de un modo que constituya una infracción a los derechos de autor, por favor mande la siguiente información a Agente de Derechos de Autor de W&C., designado como tal de conformidad con la Digital Millennium Copyright Act, 17 U.S.C. § 512 (c) (2), nombrado abajo:
						 
						Su dirección, número de teléfono y dirección de correo electrónico;
						Una descripción del trabajo con derechos de autor que usted reclama ha sido infringido;
						Una descripción de donde se localiza el supuesto material infringido;
						Una declaración suya de que usted cree de buena fe que el uso en disputa no está autorizado por el dueño de los derechos de autor, su agente o la ley;
						Una firma electrónica o física de la persona autorizada para actuar en nombre del dueño del interés de los derechos de autor; y
						Una declaración suya, hecha bajo pena de perjurio, de que la información antes mencionada en su notificación es exacta y de que usted es el dueño de los derechos de autor o está autorizado para actuar en nombre del dueño de los derechos de autor.
						 
						</dl>
						 <dl>
						<u>16.      RENUNCIA DE GARANTÍAS. EL SITIO WEB, INCLUYENDO, SIN LIMITACIÓN, TODOS LOS SERVICIOS, CONTENIDOS, FUNCIONES Y MATERIALES PROPORCIONADOS A TRAVÉS DEL SITIO WEB, SON PROPORCIONADOS "TAL COMO ESTÉN", "COMO SE PONEN A LA DISPOSICIÓN", SIN GARANTÍA DE NINGÚN TIPO, YA SEA EXPRESA O IMPLÍCITA, INCLUYENDO, SIN LIMITACIÓN, CUALQUIER GARANTÍA DE INFORMACIÓN, DATOS, SERVICIOS DE PROCESAMIENTO DE DATOS, ACCESO ILIMITADO O ININTERRUMPIDO, CUALQUIER GARANTÍA CON RESPECTO A LA DISPONIBILIDAD, INTERPRETABILIDAD, NO INTERPRETABILIDAD, EXACTITUD, PRECISIÓN, RECTITUD, PERFECCIÓN, CONCLUSIÓN, UTILIDAD, O CONTENIDO DE LA INFORMACIÓN, Y CUALQUIER GARANTÍA DE TÍTULO, NO-INFRACCIÓN, COMERCIABILIDAD O APTITUD PARA UN PROPÓSITO EN PARTICULAR, Y EN EL PRESENTE RENUNCIAMOS A CUALQUIERA Y A TODAS DICHAS GARANTÍAS, EXPRESAS E IMPLÍCITAS. NO GARANTIZAMOS QUE EL SITIO WEB O LOS SERVICIOS, CONTENIDOS, FUNCIONES O MATERIALES PROPORCIONADOS A TRAVÉS DEL SITIO WEB SERÉN OPORTUNOS, SEGUROS, ININTERRUMPIDOS O LIBRES DE ERROR, O QUE LOS DEFECTOS SERÉN CORREGIDOS. NO DAMOS GARANTÍA DE QUE EL SITIO WEB O DE QUE LOS SERVICIOS PROPORCIONADOS CUMPLIRÉN CON LOS REQUERIMIENTOS DE LOS USUARIOS. NINGÚN CONSEJO, RESULTADOS O INFORMACIÓN, YA SEA ORAL O ESCRITO, QUE USTED OBTENGA DE NOSOTROS A TRAVÉS DEL SITIO WEB CREARÉ ALGUNA GARANTÍA QUE NO HAYA SIDO ESTABLECIDA EXPRESAMENTE EN EL PRESENTE. W&C. TAMPOCO ASUME NINGUNA RESPONSABILIDAD, Y NO SERÉ RESPONSABLE DE CUALQUIER DAÑO A, O DE CUALQUIER VIRUS QUE PUDIERA INFECTAR SU EQUIPO A CAUSA DE SU ACCESO A, USO DE, O NAVEGACIÓN EN EL SITIO WEB O POR DESCARGAR CUALQUIERA DE LOS MATERIALES, DATOS, TEXTOS, IMÉGENES, CONTENIDOS DE VIDEO O CONTENIDOS DE AUDIO DEL SITIO WEB. SI USTED NO ESTÉ SATISFECHO CON EL SITIO WEB, SU ÚNICA SOLUCIÓN ES DESCONTINUAR USANDO EL SITIO WEB.
						 
						TRATAMOS DE ASEGURAR QUE LA INFORMACIÓN PUBLICADA EN EL SITIO WEB ES CORRECTA Y ACTUALIZADA. NOS RESERVAMOS EL DERECHO DE CAMBIAR O HACER CORRECCIONES A CUALQUIER INFORMACIÓN PROPORCIONADA EN EL SITIO WEB EN CUALQUIER MOMENTO Y SIN NINGÚN AVISO PREVIO. W&C. NI AVALA NI ES RESPONSABLE DE LA EXACTITUD O VERACIDAD DE CUALQUIER OPINIÓN, CONSEJO O DECLARACIÓN EN EL SITIO WEB, NI DE CUALQUIER PUBLICACIÓN OFENSIVA, DIFAMATORIA, OBSCENA, INDECENTE, ILEGAL O VIOLATORIA HECHA EN EL MISMO POR CUALQUIER PERSONA A NO SER UN EMPLEADO PORTAVOZ AUTORIZADO DE W&C. EN SU CARÉCTER OFICIAL (INCLUYENDO, SIN LIMITACIÓN, OTROS USUARIOS DEL SITIO WEB). ES SU RESPONSABILIDAD EVALUAR LA EXACTITUD, CONCLUSIÓN O UTILIDAD DE CUALQUIER INFORMACIÓN, OPINIÓN, CONSEJO U OTRO CONTENIDO DISPONIBLE A TRAVÉS DEL SITIO WEB. POR FAVOR BUSQUE EL CONSEJO DE PROFESIONALES, SEGÚN SEA APROPIADO, CON RESPECTO A LA EVALUACIÓN DE CUALQUIER INFORMACIÓN, OPINIÓN, CONSEJO U OTRO CONTENIDO ESPECÍFICO, INCLUYENDO PERO NO LIMITADO A, INFORMACIÓN, OPINIÓN, CONSEJO U OTRO CONTENIDO FINANCIERO, DE SALUD O DE ESTILO DE VIDA.
						 
						PREVIO A LA REALIZACIÓN DE UNA COMPRA O VENTA DE CUALQUIER VALOR O INVERSIÓN, LE ACONSEJAMOS QUE CONSULTE CON SU CORREDOR O CON OTRO ASESOR FINANCIERO PARA VERIFICAR PRECIOS Y OTRA INFORMACIÓN. NO TENDREMOS NINGUNA RESPONSABILIDAD DE DECISIONES DE INVERSIÓN BASADAS EN, O DE RESULTADOS OBTENIDOS DE, EL CONTENIDO PROPORCIONADO EN EL PRESENTE. NADA CONTENIDO EN EL SITIO WEB SERÉ INTERPRETADO COMO CONSEJO DE INVERSIÓN. W&C. NO ES UN CORREDOR DE BOLSA REGISTRADO NI UN CONSULTOR DE INVERSIONES Y NO DA CONSEJOS SOBRE INVERSIONES NI RECOMIENDA UN PRODUCTO SOBRE OTRO.
						 
						SIN LIMITACIÓN DE LO ANTES MENCIONADO EN ESTA SECCIÓN, W&C, Y SUS AFILIADOS, PROVEEDORES Y PERSONAS QUE OTORGAN LAS LICENCIAS NO DAN GARANTÍAS NI REPRESENTACIONES CON RESPECTO A CUALQUIER PRODUCTO O SERVICIO ORDENADO O PROPORCIONADO VÍA EL SITIO WEB, Y EN EL PRESENTE RENUNCIAN, Y USTED EN EL PRESENTE DESISTE, DE CUALQUIERA Y DE TODAS LAS GARANTÍAS Y REPRESENTACIONES HECHAS A LITERATURA EN PRODUCTOS O SERVICIOS, A PREGUNTAS HECHAS FRECUENTEMENTE EN DOCUMENTOS Y DE ALGUNA OTRA MANERA EN EL SITIO WEB O EN CORRESPONDENCIA CON W&C. O CON SUS AGENTES. CUALQUIER PRODUCTO O SERVICIO ORDENADO O PROPORCIONADO VÍA EL SITIO WEB ES PROPORCIONADO POR W&C. "TAL COMO ESTÉ", EXCEPTO AL GRADO, SI SE DIERA EL CASO, DE ESTAR DE OTRO MODO ESTABLECIDO POR ESCRITO, EN UN CONTRATO DE LICENCIA O VENTA CELEBRADO POR SEPARADO ENTRE USTED Y W&C. O SU PROVEEDOR O LA PERSONA QUE OTORGA LA LICENCIA.</u>
						</dl>
						<dl>
						<u>17.      LÍMITE DE RESPONSABILIDAD. EN NINGÚN CASO, INCLUYENDO PERO NO LIMITADO A NEGLIGENCIA, SERÉ RESPONSABLE W&C., O CUALQUIERA DE SUS DIRECTORES, FUNCIONARIOS, EMPLEADOS, AGENTES O PROVEEDORES, DEL CONTENIDO O DE LOS SERVICIOS (CONJUNTAMENTE, LAS "ENTIDADES PROTEGIDAS") DE CUALQUIER DAÑO DIRECTO, INDIRECTO, ESPECIAL, INCIDENTAL, CONSECUENTE, EJEMPLAR O PUNITIVO COMO RESULTADO DE, O DIRECTA O INDIRECTAMENTE RELACIONADO CON, EL USO DE, O LA INCAPACIDAD DE USAR EL SITIO WEB O LOS CONTENIDOS, MATERIALES Y FUNCIONES RELACIONADOS CON EL MISMO, SU PROVISIÓN DE INFORMACIÓN VÍA EL SITIO WEB, NEGOCIOS PERDIDOS O VENTAS PERDIDAS, AÚN CUANDO DICHA ENTIDAD PROTEGIDA HAYA SIDO ASESORADA SOBRE LA POSIBILIDAD DE DICHOS DAÑOS. ALGUNAS JURISDICCIONES NO PERMITEN LA LIMITACIÓN O EXCLUSIÓN DE RESPONSABILIDAD POR DAÑOS INCIDENTALES O INDIRECTOS ASÍ QUE ALGUNOS DE LAS LIMITACIONES ARRIBA MENCIONADAS NO APLICAN A ALGUNOS USUARIOS. EN NINGÚN CASO SERÉN RESPONSABLES LAS ENTIDADES PROTEGIDAS POR O EN RELACIÓN CON CUALQUIER CONTENIDO PUBLICADO, TRANSMITIDO, INTERCAMBIADO O RECIBIDO POR O EN NOMBRE DE CUALQUIER USUARIO O DE OTRA PERSONA EN O A TRAVÉS DEL SITIO WEB. EN NINGÚN CASO LA SUMA TOTAL DE LAS RESPONSABILIDADES DE LAS ENTIDADES PROTEGIDAS HACIA USTED, POR TODOS LOS DAÑOS, PÉRDIDAS Y CAUSAS DE ACCIÓN PENAL (YA SEA POR CONTRATO O POR AGRAVIO, INCLUYENDO PERO NO LIMITADO A, NEGLIGENCIA O DE ALGUNA OTRA MANERA) QUE RESULTEN DE LOS TÉRMINOS Y CONDICIONES O DEL USO QUE USTED HAGA DEL SITIO WEB, DEBERÉ EXCEDER EN LA SUMA TOTAL, LA CANTIDAD, SI LA HUBIERA, PAGADA POR USTED A W&C. POR EL USO DEL SITIO WEB O POR LA COMPRA DE PRODUCTOS VÍA EL SITIO WEB.</u>
						</dl>
						 <dl>
						<u>18.      Ataques Fotosensibles.</u> Un muy pequeño porcentaje de personas pueden experimentar un ataque al ser expuestas a ciertas imágenes visuales, como luces o dibujos intermitentes que pueden aparecer en juegos de video o en otros contenidos electrónicos o en línea. Aún personas que no tienen historia de ataques o de epilepsia pueden tener una condición no diagnosticada que puede causar estos "ataques epilépticos fotosensibles" al estar viendo juegos de video u otros contenidos electrónicos. Estos ataques tienen una variedad de síntomas, incluyendo mareos, desorientación, confusión, pérdida momentánea de conciencia, crispación de ojos o cara, visión alterada o tirones o sacudidas de brazos o piernas. Si usted experimenta cualquiera de los síntomas anteriormente mencionados, o si usted o su familia tiene historia de ataques o epilepsia, debe de dejar inmediatamente de usar el Sitio Web y consultar un doctor.
						 </dl>
						 <dl>
						<u>19.     Leyes Aplicables.</u> Nosotros controlamos y operamos el Sitio Web desde nuestras oficinas en los Estados Unidos de América. No representamos a los materiales en el Sitio Web como apropiados o disponibles para su uso en otros lugares. Las personas que escojan acceder al sitio Web desde otros lugares lo harán por su propia iniciativa y son responsables del cumplimiento de las leyes locales, si y al grado en que las leyes locales sean aplicables. Todas las partes sujetas a estos términos y condiciones renuncian a sus derechos respectivos a un juicio con jurado.
						 </dl>
						 <dl>
						<u>20.      Término.</u>  W&C. puede terminar, cambiar, suspender o descontinuar cualquier aspecto del Sitio Web o de los servicios del Sitio Web en cualquier momento. W&C. puede restringir, suspender o terminar su acceso al Sitio Web y/o a sus servicios si creemos que usted está en incumplimiento de nuestros términos y condiciones o de la ley aplicable, o por cualquier otra razón sin notificación o responsabilidad. W&C. mantiene una política que estipula la terminación, en circunstancias apropiadas, de los privilegios de uso del Sitio Web para usuarios que son violadores repetitivos de los derechos de propiedad intelectual.
						 </dl>
						 <dl>
						<u>21.      Cambios de Términos de Uso. </u> W&C. se reserva el derecho, a su sola discreción, de cambiar, modificar, añadir o quitar cualquier porción de los Términos y Condiciones, toda o en parte, en cualquier momento. Los cambios en los Términos y Condiciones serán efectivos cuando se publiquen. La continuación del uso del Sitio Web y/o de los servicios puestos a disposición en o a través del Sitio Web después de haber sido publicado cualquier cambio, será considerado como aceptación de esos cambios.
						 </dl>

					</div>
			</div>	
			<!-- INCLUDE FOOTER -->
			<?php include_once __DIR__ .'/footer.php'; ?>	
		</div>		
	</body>
</html>
	